"""Environment building blocks shared by future reset/step backends."""

from .actions import (
    ActionError,
    ActionProposal,
    PreparedAction,
    PreparedCommunication,
    PreparedCpu,
    ProposalAdapter,
)
from .energy import (
    ActualEnergyDebit,
    DowngradeSelection,
    EnergyError,
    EnergyReservation,
    UavEnergyState,
    actual_transmit_energy_j,
    debit_actual_energy,
)
from .executor import (
    CommunicationExecution,
    CpuExecution,
    DeterministicExecutor,
    ExecutedAction,
    ExecutorError,
    JointExecutionResult,
)
from .outage import OutageError, OutageResult, actual_attempt_outage
from .service import (
    CpuServiceResult,
    LinkServiceResult,
    PhysicalService,
    ServiceError,
    SlotPhysicalResult,
    TaskServiceRecord,
)

from .channel import (
    BuildingPrism,
    ChannelError,
    ChannelModel,
    ChannelSnapshot,
    PhysicalChannelModel,
    db_to_amplitude_ratio,
    db_to_power_ratio,
    dbm_to_watts,
    receiver_noise_power_w,
)
from .history import (
    ActorChannelFeatures,
    ChannelHistory,
    HistoryError,
    InterferenceHistory,
    InterferenceSnapshot,
    executor_historical_quality_mean,
)
from .lifecycle import LifecycleError, LifecycleManager, TaskLifecycle, TaskLifecycleManager, TruncationRecord
from .mobility import (
    MobilityError,
    MobilityModel,
    MobilityState,
    coordinate_wise_specular_reflection,
    reflect_coordinate,
)
from .queues import QueueInvariantError, QueueKind, QueueLocation, QueueState, TaskQueue
from .randomness import make_rng, rng_from_run_config
from .tasks import Task, TaskIdGenerator, TaskOutcome, TaskStatus
from .topology import (
    DynamicTopology,
    TopologyError,
    TopologySnapshot,
    candidate_neighbor_mask,
    pairwise_distances,
)

from .action_history import (
    PreviousActionError,
    PreviousActionFeatures,
    PreviousActionSnapshot,
)
from .environment import (
    EnvironmentError,
    FullEnvironment,
    ResetResult,
    StepResult,
    U2UMECEnvironment,
)
from .metrics import (
    ConservationSnapshot,
    EpisodeMetrics,
    EpisodeMetricsTracker,
    MetricsError,
    QueueBacklogRecord,
    SlotMetricsRecord,
)
from .observation import (
    ActionMasks,
    ActorEdgeFeatures,
    ActorObservation,
    ActorObservationBuilder,
    BRANCH_ORDER,
    IndexedQueueFeatures,
    NeighborPublicFeatures,
    ObservationBuilder,
    ObservationError,
    PrivateQueueFeatures,
    QueueSummary,
    SelfResourceFeatures,
)
from .public_history import (
    PublicHistoryError,
    PublicMessageHistory,
    PublicMessageSnapshot,
)
from .reward import (
    RewardCalculator,
    RewardError,
    RewardReferences,
    RewardTerms,
    RewardWeights,
    compute_reward,
)
from .state import (
    BuildingStateRecord,
    CentralizedState,
    CentralizedStateBuilder,
    QueueStateRecord,
    StateError,
    TaskStateRecord,
)
from .traffic import (
    ArrivalBatch,
    ArrivalEstimate,
    TrafficError,
    TrafficProcess,
)

__all__ = [
    "ActionMasks",
    "ActorEdgeFeatures",
    "ActorObservation",
    "ActorObservationBuilder",
    "ArrivalBatch",
    "ArrivalEstimate",
    "BRANCH_ORDER",
    "BuildingStateRecord",
    "CentralizedState",
    "CentralizedStateBuilder",
    "ConservationSnapshot",
    "EnvironmentError",
    "EpisodeMetrics",
    "EpisodeMetricsTracker",
    "FullEnvironment",
    "IndexedQueueFeatures",
    "MetricsError",
    "NeighborPublicFeatures",
    "ObservationBuilder",
    "ObservationError",
    "PreviousActionError",
    "PreviousActionFeatures",
    "PreviousActionSnapshot",
    "PrivateQueueFeatures",
    "PublicHistoryError",
    "PublicMessageHistory",
    "PublicMessageSnapshot",
    "QueueBacklogRecord",
    "QueueStateRecord",
    "QueueSummary",
    "ResetResult",
    "RewardCalculator",
    "RewardError",
    "RewardReferences",
    "RewardTerms",
    "RewardWeights",
    "SelfResourceFeatures",
    "SlotMetricsRecord",
    "StateError",
    "StepResult",
    "TaskStateRecord",
    "TrafficError",
    "TrafficProcess",
    "U2UMECEnvironment",
    "compute_reward",
    "ActionError",
    "ActionProposal",
    "ActualEnergyDebit",
    "CommunicationExecution",
    "CpuExecution",
    "CpuServiceResult",
    "DeterministicExecutor",
    "DowngradeSelection",
    "EnergyError",
    "EnergyReservation",
    "ExecutedAction",
    "ExecutorError",
    "JointExecutionResult",
    "LinkServiceResult",
    "OutageError",
    "OutageResult",
    "PhysicalService",
    "PreparedAction",
    "PreparedCommunication",
    "PreparedCpu",
    "ProposalAdapter",
    "ServiceError",
    "SlotPhysicalResult",
    "TaskServiceRecord",
    "UavEnergyState",
    "actual_attempt_outage",
    "actual_transmit_energy_j",
    "debit_actual_energy",
    "ActorChannelFeatures",
    "BuildingPrism",
    "ChannelError",
    "ChannelHistory",
    "ChannelModel",
    "ChannelSnapshot",
    "DynamicTopology",
    "HistoryError",
    "InterferenceHistory",
    "InterferenceSnapshot",
    "LifecycleError",
    "LifecycleManager",
    "MobilityError",
    "MobilityModel",
    "MobilityState",
    "PhysicalChannelModel",
    "QueueInvariantError",
    "QueueKind",
    "QueueLocation",
    "QueueState",
    "Task",
    "TaskIdGenerator",
    "TaskLifecycle",
    "TaskLifecycleManager",
    "TaskOutcome",
    "TaskQueue",
    "TaskStatus",
    "TopologyError",
    "TopologySnapshot",
    "TruncationRecord",
    "candidate_neighbor_mask",
    "coordinate_wise_specular_reflection",
    "db_to_amplitude_ratio",
    "db_to_power_ratio",
    "dbm_to_watts",
    "executor_historical_quality_mean",
    "make_rng",
    "pairwise_distances",
    "receiver_noise_power_w",
    "reflect_coordinate",
    "rng_from_run_config",
]
